CREATE TABLE STUDENTS 
(
  PERSONID  VARCHAR2(10),
  SHAPE SDO_GEOMETRY,
  CONSTRAINT STUDENTS_PK PRIMARY KEY (PERSONID)
);

CREATE TABLE ANNOUNCEMENTSYSTEMS
(
  ASID  VARCHAR2(10),
  RADIUS INTEGER,
  CENTER SDO_GEOMETRY,
  SHAPE SDO_GEOMETRY,
  CONSTRAINT AS_PK PRIMARY KEY (ASID)
);

CREATE TABLE BUILDINGS
(
  BUILDINGID  VARCHAR2(10),
  BUILDING_NAME VARCHAR2(50),
  VERTICES_COUNT  INTEGER,
  SHAPE SDO_GEOMETRY,
  CONSTRAINT BUILDINGS_PK PRIMARY KEY (BUILDINGID)
);

INSERT INTO USER_SDO_GEOM_METADATA 
  VALUES ('BUILDINGS', 'SHAPE', SDO_DIM_ARRAY( SDO_DIM_ELEMENT('X', 0, 20, 0.005), SDO_DIM_ELEMENT('Y', 0, 20, 0.005)), NULL);
  
INSERT INTO USER_SDO_GEOM_METADATA 
  VALUES ('STUDENTS', 'SHAPE', SDO_DIM_ARRAY( SDO_DIM_ELEMENT('X', 0, 20, 0.005), SDO_DIM_ELEMENT('Y', 0, 20, 0.005)), NULL);
  
INSERT INTO USER_SDO_GEOM_METADATA 
  VALUES ('ANNOUNCEMENTSYSTEMS', 'SHAPE', SDO_DIM_ARRAY( SDO_DIM_ELEMENT('X', 0, 20, 0.005), SDO_DIM_ELEMENT('Y', 0, 20, 0.005)), NULL);
INSERT INTO USER_SDO_GEOM_METADATA 
  VALUES ('ANNOUNCEMENTSYSTEMS', 'CENTER', SDO_DIM_ARRAY( SDO_DIM_ELEMENT('X', 0, 20, 0.005), SDO_DIM_ELEMENT('Y', 0, 20, 0.005)), NULL);  
  
CREATE INDEX STUDENTS_INDEX ON STUDENTS(SHAPE) 
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
  
CREATE INDEX BUILDINGS_INDEX ON BUILDINGS(SHAPE)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX;
      
CREATE INDEX ANNOUNCEMENTSYSTEMS_INDEX ON ANNOUNCEMENTSYSTEMS(SHAPE)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX;     
   
CREATE INDEX AS_INDEX_CENTER ON ANNOUNCEMENTSYSTEMS(CENTER)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX;     

 
