DROP INDEX STUDENTS_INDEX;
DROP INDEX BUILDINGS_INDEX;
DROP INDEX ANNOUNCEMENTSYSTEMS_INDEX;
DROP INDEX AS_INDEX_CENTER;

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'BUILDINGS';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'STUDENTS';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'ANNOUNCEMENTSYSTEMS';

DROP TABLE BUILDINGS;
DROP TABLE STUDENTS;
DROP TABLE ANNOUNCEMENTSYSTEMS;
